SEProject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('onlinetest.urls')),
]

onlinetest/urls.py
from django.conf.urls import url
from SEProject import settings
from . import views
from django.conf.urls.static import static


app_name = 'onlinetest' 

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^studentlogin$', views.studentlogin, name='studentlogin'),
    url(r'^clientlogin$', views.clientlogin, name='clientlogin'),
    url(r'^clientloginVal$', views.clientloginVal, name='clientloginVal'),
    url(r'^clientregister$', views.clientregister, name='clientregister'),
    url(r'^adminhome$', views.adminhome, name='adminhome'),
    url(r'^home$', views.home, name='home'),
    url(r'^studentReg$', views.studentReg, name='studentReg'),
    url(r'^addtest$', views.addtest, name='addtest'),
    url(r'^(?P<test_id>[0-9]+)/deletetest/$', views.deletetest, name='deletetest'),
    url(r'^studentLogincheck$', views.studentLogincheck, name='studentLogincheck'),
    url(r'^studenthome$', views.studenthome, name='studenthome'),
    url(r'^yourtest$', views.yourtest, name='yourtest'),
    url(r'^studentRegSave', views.studentRegSave, name='studentRegSave'),
    url(r'^studentInfo', views.studentInfo, name='studentInfo'),
    url(r'^clientlogout', views.clientlogout, name='clientlogout'),
    url(r'^studentmarksAnalysis', views.studentmarksAnalysis, name='studentmarksAnalysis'),
    url(r'^studentmarksGraphAnalysis', views.studentmarksGraphAnalysis, name='studentmarksGraphAnalysis'),
    url(r'^testMarksGraph', views.testMarksGraph, name='testMarksGraph'),
    url(r'^studentlogout', views.studentlogout, name='studentlogout'),
    url(r'^simple_upload', views.simple_upload, name='simple_upload'),
    url(r'^paper_submit$',views.paper_submit, name='paper_submit'),
    url(r'^studentreview$',views.studentreview, name='studentreview'),
    url(r'^add_review',views.add_review, name='add_review'),
    url(r'^client_review',views.client_review, name='client_review'),
    url(r'^studentseeanswers', views.studentseeanswers, name='studentseeanswers'),
    url(r'^update_scores',views.update_scores, name='update_scores'),


    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

onlinetest/models.py
from django.contrib.auth.models import Permission
from django.db import models
from datetime import datetime
import os
import random


class clientsTable(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=120, unique=True)
    contactNumber = models.CharField(max_length=15)
    pwd = models.CharField(max_length=80)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.email


class testDetails(models.Model):
    test_id = models.CharField(max_length=50, unique=True)
    client_id = models.CharField(max_length=100, default=0)
    testtitle = models.CharField(max_length=250)
    testduration = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now, blank=True)
    re_answers = models.CharField(max_length=120,default="E"*120)

    def __str__(self):
        return self.test_id


class studentProfile(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=120, unique=True)
    password = models.CharField(max_length=50, default=None)
    rollno = models.CharField(max_length=50, default=None)
    client = models.CharField(max_length=50, default=None)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.email


class question(models.Model):
    question_id = models.CharField(max_length=30)
    question = models.CharField(max_length=500)
    option1 = models.CharField(max_length=100)
    option2 = models.CharField(max_length=100)
    option3 = models.CharField(max_length=100)
    option4 = models.CharField(max_length=100)
    answer = models.CharField(max_length=500)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.question    

class studentMark(models.Model):
    studentid = models.CharField(max_length=120,default=0)
    ques_paper_id = models.CharField(max_length=50)
    marks = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    testtitle = models.CharField(max_length=50)
    client = models.CharField(max_length=50, default=None)
    date = models.DateTimeField(default=datetime.now, blank=True)
    
    answers = models.CharField(max_length=120,default="5"*120)
    comments = models.CharField(max_length=3000,default="")

    def __str__(self):
        return self.email 

onlinetest/forms.py
import datetime
from django import forms
from django.contrib.auth.models import User

# for client registration
class clientRegisterForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.CharField(max_length=120)
    contactNumber = forms.CharField(max_length=15)
    pwd= forms.CharField(max_length=80)

# for saving test detials
class savetestdetails(forms.Form):
    testtitle = forms.CharField(max_length=100)
    testduration = forms.CharField(max_length=10)

#for submitting marks
class saveMarks(forms.Form):
    totalmarks = forms.CharField(max_length=20)
    answers = forms.CharField(max_length=120)
	
# for client login
class LoginForm(forms.Form):
    email=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

#for student login
class StudenLoginForm(forms.Form):
    email = forms.CharField(max_length=120)
    password = forms.CharField(max_length=50)
    client = forms.CharField(max_length=50)

#for student registration
class StudentRegForm(forms.Form):
    email = forms.CharField(max_length=120)
    name = forms.CharField(max_length=100)
    rollno = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)
    client = forms.CharField(max_length=50)

# for validating test ID
class TestIdVal(forms.Form):
    test_id=forms.CharField(max_length = 250)

class CommentForms(forms.Form):
    comments=forms.CharField(max_length=3000)

class getClientReview(forms.Form):
    ques_paper_id = forms.CharField(max_length=20)
    student_id = forms.CharField(max_length=120)


class saveCorrectedAnswers(forms.Form):
    test_id = forms.CharField(max_length=20)
    corrected_ans = forms.CharField(max_length=120)

onlinetest/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, get_object_or_404, render_to_response
# This may be used instead of Users.DoesNotExist
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import clientRegisterForm, StudenLoginForm, saveMarks, TestIdVal, LoginForm, StudentRegForm, StudenLoginForm, savetestdetails, getClientReview, CommentForms, saveCorrectedAnswers

from django.views.decorators.csrf import csrf_protect
# for older versoins of Django use:
# from django.core.urlresolvers import reverse
import ast
import random
import string
from .models import studentProfile, question, testDetails, studentMark, clientsTable
import onlinetest.file_reader
from django.utils.timezone import datetime
import random
# from Crypto.cipher import AES
import time
# for redirecting to home page
from django.contrib import messages

def check_if_review_needed(stuMarks):
	result = ""
	for student in stuMarks:
		comments = student.comments
		comments = comments.split("___")
		if len(comments)==0:
			if comments[0]=="":
				result+='0'
			else:
				result+='1'
		else:
			result+='1'
	return result 

def index(request):
	try:
		return render(request, 'onlinetest/index.html')
	except:
		return HttpResponse("Something went wrong")

# for redirecting to student login page


def studentlogin(request):
	try:
		return render(request, 'onlinetest/studentlogin.html')
	except:
		return HttpResponse("Something went wrong")

# for redirecting to client registration page


def clientregister(request):
	try:
		return render(request, 'onlinetest/clientregister.html')
	except:
		return HttpResponse("Something went wrong")

# for redirecting to client login page


def clientlogin(request):
	try:
		return render(request, 'onlinetest/clientlogin.html', {'login_message': ""})
	except:
		return HttpResponse("Something went wrong")


def studentmarksAnalysis(request):
	flag = 0
	try:
		uid = request.session['user_id']
		client1 = clientsTable.objects.get(pk=uid)
		stuMarks = studentMark.objects.filter(client=uid)
		flag = check_if_review_needed(stuMarks)
		return render(request, 'onlinetest/studentmarks.html', {'client_id': client1, 'stuMarks': stuMarks, 'flag': flag})
	except Exception as e:
		print(e)
		return HttpResponse("Something went wrong")

def studentmarksGraphAnalysis(request):
	try:
		uid = request.session['user_id']
		client1 = clientsTable.objects.get(pk=uid)
		tests = testDetails.objects.filter(client_id=uid)
		return render(request, 'onlinetest/studentgraphmarks.html', {'client_id': client1, 'tests':tests})
	except:
		return HttpResponse("Something went wrong")
        

def testMarksGraph(request):
	try:
		test_id = request.GET.get('test_id')
		uid = request.session['user_id']
		stuMarks = studentMark.objects.filter(client=uid).filter(ques_paper_id=test_id)

		num_ques = 0
		try:
			num_ques = len(stuMarks[0].answers)
		except:
			pass

		stuMarksDict = dict()

		for i in stuMarks:
			stuMarksDict[i.email] = i.marks

		return render(request, 
			   		  'onlinetest/studentgraphmarksdisp.html',
			   		  {'client_id': uid,
					   'stuMarksDict': stuMarksDict,
					   'test_id':test_id,
					   'num_ques':num_ques})

	except Exception as e:
		print(e)
		return HttpResponse("Something went wrong")


def addtest(request):
	try:
		uid = request.session['user_id']
		client = clientsTable.objects.get(pk=uid)
		return render(request, 'onlinetest/addtest.html', {'client_id': client})
	except:
		return HttpResponse("Something went wrong")


def studentInfo(request):
	try:
		uid = request.session['user_id']
		client1 = clientsTable.objects.get(pk=uid)
		stuInfo = studentMark.objects.filter(client=uid)
		# print(stuInfo,client1,uid)
		return render(request, 'onlinetest/studentinfo.html', {'client_id': client1, 'stuInfo': stuInfo})
	except:
		return HttpResponse("Something went wrong")

# for redirecting to testID page


def studenthome(request):
	try:
		if request.session.has_key('test_id'):
			return render(request, 'onlinetest/studenthome.html')
		else:
			return HttpResponseRedirect(reverse('onlinetest:studentlogin'))
	except:
		return HttpResponse("Something went wrong")


def home(request):
	try:
		if request.session.has_key('user_id'):
			uid = request.session['user_id']
			try:
				clientobj = clientsTable.objects.get(pk=uid)
				testinfo_list = testDetails.objects.filter(client_id=uid)
				paginator = Paginator(testinfo_list, 3) # Show 5 tests per page

				page = request.GET.get('page')
				try:
					testinfo = paginator.page(page)
				except PageNotAnInteger:
				# If page is not an integer, deliver first page.
					testinfo = paginator.page(1)
				except EmptyPage:
				# If page is out of range (e.g. 9999), deliver last page of results.
					testinfo = paginator.page(paginator.num_pages)
				return render(request, 'onlinetest/clientadmin.html', {'client_id': clientobj, 'test': testinfo})
			except clientsTable.DoesNotExist:
				return HttpResponse("User not found")
		else:
			return render(request, 'onlinetest/index.html')
	except:
		return HttpResponse("Something went wrong")


# for validating client login and redirecting to admin panel


def clientloginVal(request):
	try:
		if request.method == 'POST':
			log = LoginForm(request.POST)
			if log.is_valid():
				try:
					user = clientsTable.objects.get(email=log.cleaned_data.get(
						'email').strip(), pwd=log.cleaned_data.get('pwd').strip())
					request.session['user_id'] = user.id
					useremail = user.email
					return HttpResponseRedirect(reverse('onlinetest:home'))
				except clientsTable.DoesNotExist:
				        return render(request, 'onlinetest/clientlogin.html', {'login_message': "Wrong username or password"})
	except:
		return render(request, 'onlinetest/clientlogin.html', {'login_message': "Wrong username or password"})

# for client registration and redirecting to admin panel


def adminhome(request):
	try:
		if request.method == 'POST':
			signup = clientRegisterForm(request.POST)
			if signup.is_valid():
				try:
					p = clientsTable(
						name=signup.cleaned_data.get('name').strip(),
						email=signup.cleaned_data.get('email').strip(),
						contactNumber=signup.cleaned_data.get(
							'contactNumber').strip(),
						pwd=signup.cleaned_data.get('pwd').strip(),
					)
					p.save()
					request.session['user_id'] = p.id
					# print("*********************************",p.id)
				except clientsTable.DoesNotExist:
					return HttpResponse("Email already registered")
		return HttpResponseRedirect(reverse('onlinetest:home'))
	except:
		return HttpResponse("Email already registed")

# for adding test details


def simple_upload(request):
	try:
		form = savetestdetails(request.POST or None, request.FILES or None)
		if request.method == 'POST' and request.FILES['myfile'] and form.is_valid():
			now = str(datetime.now().strftime("%Y%m%d%H%M"))
			now = now + str(request.session['user_id'])
			myfile = request.FILES['myfile']
			ext = myfile.name[myfile.name.rfind('.'):]
			fs = FileSystemStorage()
			filename = fs.save(now + ext, myfile)
			re_answers = onlinetest.file_reader.file_to_db(
				filename, str(request.session['user_id']), now)
			uploaded_file_url = fs.url(filename)
			# count1 = question.objects.filter(question_id=now)
			p = testDetails(
				test_id=now,
				client_id=str(request.session['user_id']).strip(),
				testtitle=form.cleaned_data.get('testtitle').strip(),
				testduration=form.cleaned_data.get('testduration').strip(),
				re_answers=re_answers,
				# noOfQuestions = abc,
			)
			p.save()
			return render(request, 'onlinetest/addtest.html', {
				'uploaded_file_url': now,
			})
		return render(request, 'onlinetest/addtest.html', {'client_id': client})
	except Exception as e:
		print(e)
		return HttpResponse("Something went wrong")

# for deleting test

def deletetest(request, test_id):
	try:
		test = testDetails.objects.get(pk=test_id)
		questions = question.objects.filter(question_id=test.test_id)
		deleteMarks = studentMark.objects.filter(ques_paper_id=test.test_id)
		test.delete()
		for i in questions:
			questions.delete()

		for j in deleteMarks:
			deleteMarks.delete()
		return HttpResponseRedirect(reverse('onlinetest:home'))
	except:
		return HttpResponse("Cannot Delete Test")


def clientadmin(request):
	try:
		if not request.user.is_authenticated():
			return render(request, 'onlinetest/clientlogin.html', {'login_message':""})
		else:
			tests = Test.objects.filter(user=request.user)
			return render(request, 'onlinetest/clientadmin.html', {'tests': tests})
	except:
		return HttpResponse("Something went wrong")




def studentreview(request):
	try:
		studentid = request.session['studentuid']
		testid = request.session['test_id']
		# user = studentMark.objects.get(pk=studentid)
		ques = question.objects.filter(question_id=testid)
		# print(testid)
		user = studentMark.objects.filter(studentid=studentid).filter(ques_paper_id=testid)[0]
		answers = user.answers
		# re_answers = user.re_answers
		re_answers = testDetails.objects.filter(test_id=testid)[0].re_answers
		noOfQuestions = ques.count()
		marks = user.marks
		# print(request.session)
		return render(request, 'onlinetest/review.html', {'studentid':studentid, 'testid':testid, 'user_id':user, 'ques':ques,'answers':answers,'re_answers':re_answers,'marks':marks, 'noOfQuestions': noOfQuestions })
		
		# return render(request, 'onlinetest/review.html', {'studentid':studentid, 'testid':testid, 'user':user, 'ques':ques })
	except Exception as e:
		print(e)
		return HttpResponse("Something went wrong")

def studentseeanswers(request):
	try:
		studentid = request.session['studentuid']
		testid = request.session['test_id']

onlinetest/templates/onlinetest/clientlogin.html
{% extends "onlinetest/header.html" %} {% block content %}
<br><br>
<div class="container">
    <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:clientloginVal' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <center>
                    <h3>Login to your Account</h3><br>
                </center>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="text" class="form-control input-lg" name="email" autofocus placeholder="Email" required>
                </div>
                <div class="form-group">
                    <input type="password" class="form-control input-lg" name="pwd" placeholder="Password" required>
                    <p style="color:red;">{{ login_message }}</p>
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <center>
                        <button class="btn btn-primary" type="submit"><b style="font-size: larger">Log In</b></button>&nbsp;
                        <b>or</b>&nbsp;
                        <a href="/clientregister" class="btn btn-warning" type="submit"><b style="font-size: larger">Sign Up</b></a>
                    </center>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

onlinetest/templates/onlinetest/clientregister.html
{% extends "onlinetest/header.html" %} {% block content %}
<br>
<div class="container">
    <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:adminhome' %}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12" style="text-align: center">
                <h3>Register for conducting a Test</h3><br>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <input type="text" autofocus class="form-control input-lg" name="name" placeholder="Name" required />
                </div>
                <div class="form-group">
                    <input type="email" autofocus class="form-control input-lg" name="email" placeholder="Email-ID" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
                        required />
                </div>
                <div class="form-group">
                    <input type="text" class="form-control input-lg" pattern="[789][0-9]{9}" maxlength="11" name="contactNumber" placeholder="Contact Number"
                        required>
                </div>
                <div class="form-group">
                    <input type="password" id="password" class="form-control input-lg" name="pwd" placeholder="Create a Password" required>
                </div>
                <div class="form-group">
                    <input type="password" id="password_confirm" oninput="check(this)" class="form-control input-lg" name="cpwd" placeholder="Confirm-Password"
                        required>
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <center>
                        <button class="btn btn-primary"><b style="font-size: larger">Sign Up</b></button>
                        <b>or</b>&nbsp;
                        <a href="/clientlogin" class="btn btn-warning" type="submit"><b style="font-size: larger">Sign In</b></a>
                    </center>
                </div>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </form>
</div>
<br>
<script language='javascript' type='text/javascript'>
    function check(input) {
        if (input.value != document.getElementById('password').value) {
            input.setCustomValidity('Password Must be Matching.');
        } else {
            // input is valid -- reset the error message
            input.setCustomValidity('');
        }
    }

</script>
{% endblock %}

onlinetest/templates/onlinetest/header.html
<!DOCTYPE html> {% load static %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title> Online Examination System
    </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600italic,700,800' rel='stylesheet'
        type='text/css'>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Candal|Alegreya+Sans">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'onlinetest/css/style1.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'onlinetest/css/imagehover.min.css' %}" type="text/css" />
</head>

<body style="height: 100%">
    <div style="min-height: 87.6%">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
                    <a class="navbar-brand" href="/">Online EXAMINATION</a>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/">HOME</a></li>
                        <li><a href="/studentlogin">STUDENTS</a></li>
                        <li><a href="/clientlogin">CLIENTS</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %} {% endblock %}
    </div>
    <div style="text-align: center">
        <footer id="footer" class="footer" style="padding: 17px 0">
            SE Project - 2019
            <div class="credits">
                <a href="https://www.pes.edu"><b> PES University</b></a><br>
            </div>
        </footer>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" Async></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" Async integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>

</html>

onlinetest/templates/onlinetest/index.html
{% extends "onlinetest/header.html" %} {% block content %}

<div class="banner">
    <div class="bg-color">
        <div class="container">
            <div class="row">
                <div class="banner-text text-center">
                    <div class="text-border">
                        <h2 class="text-dec">Read, Analyze, Answer</h2>
                    </div>
                    <div class="intro-para text-center quote">
                        <p class="big-text">Push yourself, because no one else is going to do it for you.</p>
                        <p class="small-text">Don't stress, Do your best, Forget the rest.</p>
                        <a href="/studentlogin" class="btn btn-success btn-lg">Student Login</a>
                        <a href="/clientlogin" class="btn btn-success btn-lg">Client Login</a>
                        <a href="/clientregister" class="btn btn-success btn-lg">Client Signup</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

onlinetest/templates/onlinetest/studenthome.html
{% extends "onlinetest/header.html" %} {% block content %}
<br>
<center><h2><b>Test ID : {{ testid.test_id }} </b></h2></center>
<center><b>{{ unsuccess }} </b> </center>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <center>
                <h3>Register</h3>
            </center>
            <form class="form col-md-12" method="POST" action="{% url 'onlinetest:studentRegSave' %}">
                {% csrf_token %}
                <center>
                    <div class="form-group">
                        <input type="text" class="form-control"  name="name" placeholder="Your Name" required>
                    </div>
                    <div class="form-group">
                        <input type="email"  name="email" class="form-control" placeholder="Email-ID" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control"  name="password" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control"  name="rollno" placeholder="Roll No or ID" required>
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control"  name="client" value="{{ testid.client_id }}">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-info"><b>Start Test</b></button>
                    </div>
                </center>
            </form>
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <center>
                <h3> Sign In</h3>
            </center>
            <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:studentLogincheck' %}">
                {% csrf_token %}
                <center>
                    <div class="form-group">
                        <input type="email" class="form-control"  name="email" autofocus placeholder="Email-ID" required>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control"  name="password" placeholder="Password" required>
			<p style="color:red;">{{ login_message }}</p>
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control"  name="client" value="{{ testid.client_id }}">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-info" type="submit"><b>Start Test</b></button>
                    </div>
                </center>
            </form>
        </div>
    </div>
</div>

{% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
{% endblock %}

onlinetest/templates/onlinetest/studentlogin.html
{% extends "onlinetest/header.html" %} {% block content %}
<br>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form class="form col-md-12 center-block" method="POST" action="{% url 'onlinetest:studentReg' %}">
                {% csrf_token %}
                <center>
				    <h5> Enter the unique test ID provided by your examiner here </h5>
                    <input type="text" class="form-control input-lg" name="test_id"  autofocus placeholder="Test ID" required><br>
                </center>
                <button class="btn btn-primary btn-lg" type="submit"><b>Start Test</b></button><br>
                <br>
                <h3> Common Instructions </h3>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <ul>
                <li>1) Close all tabs in your browser.</li>
                <li>2) Do not refresh or close the window during the test.</li>
                <li>3) Students must not stop the session and then return to it.</li>
                <li>4) Make sure that you have a stable internet connection.</li>
                <li>6) The student may not use his or her textbook, course notes, or receive help from a proctor or any other
                    outside source. </li>
                </li>
                <li><br></li>
            </ul>
        </div>
    </div>
</div>
{% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}

        {% endfor %}

    {% endif %}
{% endblock %}